version: '3.7'

networks:
  cluster:

services:
  bp:
    build:
      context: .
      dockerfile: bp.Dockerfile
    ports: 
      - "127.0.0.1:8000:8000"
    volumes:
      - ${DATA_DIR}:/app/data/mainnet/training
    networks:
      - cluster
    entrypoint: ["python3.9", "api_server.py"]
                
  bp-bg:
    build:
      context: .
      dockerfile: bp-bg.Dockerfile
    ports: 
      - "127.0.0.1:8000:8000"
    networks:
      - cluster
  
  blockgauge:
    image: ghcr.io/blockprint-collective/blockgauge
    command: >-
      --lighthouse-url ${BN_URL:-localhost:5052} 
      --blockprint-url ${BP_URL:-bp-bg:8000} 
    networks:
      - cluster      

                

        
        